apps/authentication/urls.py
"""Auth models."""

# Django
from django.contrib.auth.views import (
    LogoutView,
    LoginView,
)
from django.urls import path

# Views
from apps.authentication.views import (
    SignUpView,
    HitmanListView,
    HitmanDetailView,
    AddFromManagersGroupView,
)

app_name = "auth"

urlpatterns = (
    path(
        route="",
        view=LoginView.as_view(
            template_name="authentication/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path(
        route="logout/",
        view=LogoutView.as_view(),
        name="logout",
    ),
    path(
        route="register/",
        view=SignUpView.as_view(),
        name="register",
    ),
    path(
        route="hitman/",
        view=HitmanListView.as_view(),
        name="hitman_list",
    ),
    path(
        route="hitman/<int:pk>/",
        view=HitmanDetailView.as_view(),
        name="hitman_detail",
    ),
    path(
        route="hitman/<int:pk>/add/managers/",
        view=AddFromManagersGroupView.as_view(),
        name="hitman_add_managers",
    ),
)

apps/hit/urls.py
"""Auth models."""

# Django
from django.urls import path

# Views
from apps.hit.views import (
    HitsListView,
    HitsDetailView,
    HitsCreateView,
    HitsUpdateView,
    HitBulkUpdateView,
)

app_name = "hit"

urlpatterns = (
    path(route="hits/", view=HitsListView.as_view(), name="hits_list"),
    path(route="hits/<int:pk>/", view=HitsDetailView.as_view(), name="hits_detail"),
    path(
        route="hits/<int:pk>/update/", view=HitsUpdateView.as_view(), name="hits_update"
    ),
    path(route="hits/create/", view=HitsCreateView.as_view(), name="hits_create"),
    path(route="hits/bulk/", view=HitBulkUpdateView.as_view(), name="hits_bulk"),
)

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib.auth.decorators import login_required

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.authentication.urls")),
    path("", include("apps.hit.urls")),
    path("", include("apps.bulk.urls")),
    path("", include("apps.fsm.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<!--begin::Head-->
<head>
    <meta charset="utf-8"/>
    <title>:: SPY :: AGENCY</title>
    <meta name="description" content="Page with empty content"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

    {% block css %}
        {% include "base/css.html" %}
    {% endblock %}

</head>
<!--end::Head-->

<!--begin::Body-->
<body id="kt_body"
      class="header-fixed header-mobile-fixed subheader-enabled subheader-fixed aside-enabled aside-fixed aside-minimize-hoverable page-loading">

    <!--begin::Main-->

    <div class="d-flex flex-column flex-root">
        <!--begin::Page-->
        <div class="d-flex flex-row flex-column-fluid page">

            {% include "base/sidebar.html" %}

            <!--begin::Wrapper-->
            <div class="d-flex flex-column flex-row-fluid wrapper" id="kt_wrapper">
                {% include "base/header.html" %}

                <!--begin::Content-->
                <div class="content  d-flex flex-column flex-column-fluid" id="kt_content">
                    {% include "base/navbar.html" %}

                    <!--begin::Entry-->
                    <div class="d-flex flex-column-fluid">
                        <!--begin::Container-->
                        <div class="container">
                            {% for message in messages %}
                            <i class="d-none toast-message" data-tags="{{ message.tags }}" data-message="{{ message }}"></i>
                            {% endfor %}
                            {% block content %}
                                <p>Page content goes here...</p>
                            {% endblock %}
                            {% block modals %}{% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include "base/user_panel.html" %}
    {% block panels %}
    {% endblock %}
    {% block js %}
        {% include "base/js.html" %}
    {% endblock %}
</body>
<!--end::Body-->
</html>

templates/base/base_confirm_delete.html
{% extends 'base/base.html' %}


{% block content %}
<div class="alert alert-custom alert-light-danger mb-5" role="alert">
  <div class="alert-icon"><i class="flaticon-warning"></i></div>
  <div class="alert-text">
    <h2>¿Este seguro de eliminar este registro?</h2>
    <p>** Recuerde que esta acción puede afectar otras funciones del sistema. **</p>
    <h4>Se eliminará el siguiente elemento: <span class="text-info font-weight-bolder">{{ object }}</span></h4>
    <div class="mt-5">
      <form action="" method="POST">
        {% csrf_token %}
        {% if site.urls.detail %}
        <a href="{{ site.urls.detail }}" class="btn btn-primary">Cancelar</a>
        {% endif %}
        <button type="submit" class="btn btn-danger">Eliminar</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/base/base_detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block page_title %}{{ object|capfirst|truncatechars:30 }}{% endblock %}

{% block content %}
    <div class="card card-custom card-sticky" id="kt_page_sticky_card">
        <div class="card-header">
            <div class="card-title">
                <h3 class="card-label">
                    {{ object|capfirst }} <i class="mr-2"></i>
                </h3>
            </div>
            <div class="card-toolbar">
                {% block detail_actions %}
                    {% if site.urls.delete %}
                        <a href="{{ site.urls.delete }}" class="btn btn-light-danger font-weight-bolder mr-2">
                            <i class="fas fa-times icon-sm"></i>Delete
                        </a>
                    {% endif %}
                    {% if site.urls.update %}
                        <a href="{{ site.urls.update }}" class="btn btn-light-primary font-weight-bolder mr-2">
                            <i class="fas fa-pen icon-sm"></i>Update
                        </a>
                    {% endif %}
                    {% if site.urls.create %}
                        <a href="{{ site.urls.create }}" class="btn btn-primary font-weight-bolder mr-2">
                            <i class="fas fa-plus icon-sm"></i>
                            Create new
                        </a>
                    {% endif %}
                {% endblock %}
                <div class="btn-group">

                    <button type="button" class="btn btn-info dropdown-toggle dropdown-toggle-split"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-check icon-sm"></i> STATUS
                    </button>
                    <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right">
                        <ul class="nav nav-hover flex-column">
                            {% block transition_menu %}
                                {% for transition in object.get_available_state_transitions %}
                                    {% if request.user %}
                                        <li class="nav-item">
                                            <a href="#" data-transition="{{ transition.name }}"
                                               data-input="{{ transition.custom.input }}"
                                               data-placeholder="{{ transition.custom.placeholder }}"
                                               class="nav-link transition">
                                                <i class="{{ transition.custom.icon|default:'far fa-hand-point-right' }} icon-lg mr-3"></i>
                                                <span class="nav-text">{{ transition.custom.verbose }}</span>
                                            </a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            {% endblock %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body">
            {% include "fsm/workflow.html" %}
            {% block detail %}
                {% for row in site.results %}
                    <div class="row">
                        {% for label, value in row.fields %}
                            <div class="col-md-{{ row.cols }}">
                                <div class="form-group">
                                    <label>{{ label|capfirst }}</label>
                                    <input class="form-control" type="text" value="{{ value|default_if_none:'' }}"
                                           readonly>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            {% endblock %}
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Creación</label>
                        <p class="form-control-static">
                            {{ object.created_date|default_if_none:"" }}
                            <strong>por</strong> {{ object.created_user|default_if_none:"" }}
                        </p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Ultima modificación</label>
                        <p class="form-control-static">
                            {{ object.modified_date|default_if_none:"" }}
                            <strong>por</strong> {{ object.modified_user|default_if_none:"" }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block modals %}
    <div class="insoles-detail-modal">
        <div class="modal fade text-left" id="insoles-detail" tabindex="3" role="dialog" aria-labelledby="modalLabel"
             aria-hidden="true">
            <div class="modal-dialog modal-xl modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="modalLabel">Detalle </h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <i class="bx bx-x"></i>
                        </button>
                    </div>
                    <div class="modal-body">

                    </div>
                    <div class="modal-footer">

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}



{% block js %}
    {{ block.super }}
    <script src="{% static 'assets/js/apps/insoles_detail.js' %}"></script>
{% endblock %}

templates/base/base_error.html
<!DOCTYPE html>
<html lang="es" >
    <!--begin::Head-->
    <head>
        <meta charset="utf-8"/>
        <title>Sim | Error</title>
        <meta name="description" content=""/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        {% include "base/css.html" %}
    </head>
    <!--end::Head-->

    <!--begin::Body-->
    <body  id="kt_body"  class="header-fixed header-mobile-fixed subheader-enabled subheader-fixed aside-enabled aside-fixed aside-minimize-hoverable page-loading"  >
    	<!--begin::Main-->
        <div class="d-flex flex-column flex-root">
            <!--begin::Error-->
            {% block error %}{% endblock %}
            <!--end::Error-->
        </div>
        <!--end::Main-->
        {% include "base/js.html" %}
    </body>
    <!--end::Body-->
</html>

templates/base/base_form.html
{% extends 'base/base.html' %}

{% load static %}
{% block css %}
    {{ block.super }}
    <link href="{% static 'assets/css/forms/validation.css' %}" rel="stylesheet"/>
    <!--<link href="{% static 'assets/css/forms/validation.css' %}" rel="stylesheet" />-->
{% endblock %}


{% block content %}
<div class="card card-custom card-sticky" id="kt_page_sticky_card">
    <div class="card-header">
        <div class="card-title">
            <h3 class="card-label">
                {{ site.title|capfirst }} <i class="mr-2"></i>
            </h3>
        </div>
        <div class="card-toolbar">
            {% if object and site.urls.delete %}
                <a href="{{ site.urls.delete }}" class="btn btn-light-danger font-weight-bolder mr-2">
                    <i class="fas fa-times icon-sm"></i>Eliminar
                </a>
            {% endif %}
            <div class="btn-group">
                <button type="submit" form="main-form" class="btn btn-primary font-weight-bolder">
                    <i class="fas fa-check icon-sm"></i>Guardar
                </button>
            </div>
        </div>
    </div>
    <div class="card-body">
        <form id="main-form" data-errors="{{ form.errors.as_json }}" action="" method="POST"
                enctype="multipart/form-data" novalidate>
            {% csrf_token %}

            {% block form %}
                {% include 'forms/form.html' with form=form %}
            {% endblock %}

            {% block extra_forms %}{% endblock %}
        </form>
    </div>
</div>
{% endblock %}

{% block modals %}
    <div class="insoles-forms">
        <div class="modal fade text-left" id="insoles-forms" tabindex="3" role="dialog" aria-labelledby="modalLabel"
             aria-hidden="true">
            <div class="modal-dialog modal-xl modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="modalLabel">Crear nuevo </h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <i class="bx bx-x"></i>
                        </button>
                    </div>
                    <form id="insoles-form" action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="modal-body">

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                <i class="bx bx-x d-block d-sm-none"></i>
                                <span class="d-none d-sm-block">Cancelar</span>
                            </button>
                            <button type="submit" class="btn btn-primary ml-1">
                                <i class="bx bx-check d-block d-sm-none"></i>
                                <span class="d-none d-sm-block">Crear</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
    {{ block.super }}
    <script src="{% static 'vendors/formset/jquery.formset.js' %}"></script>
    <script src="{% static 'vendors/formset/formsets.init.js' %}"></script>
    <script src="{% static 'assets/js/apps/insoles.js' %}"></script>
    <script src="{% static 'assets/js/apps/indexing.js' %}"></script>
    <script src="{% static 'assets/js/apps/taxpayers.js' %}"></script>

{% endblock %}

templates/base/css.html
{% load static %}

<!--begin::Fonts-->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700"/>        <!--end::Fonts-->

<!--begin::Page Vendors Styles(used by this page)-->
<link href="{% static 'assets/css/pages/error.css' %}" rel="stylesheet" type="text/css"/>
<!--end::Page Vendors Styles-->


<!--begin::Global Theme Styles(used by all pages)-->
<link href="{% static 'vendors/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/css/style.bundle.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/css/elements/statebar.css' %}" rel="stylesheet" type="text/css"/>
<!--end::Global Theme Styles-->

<!--begin::Layout Themes(used by all pages)-->
<link href="{% static 'assets/css/layout/header/base/light.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/css/layout/header/menu/light.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/css/layout/brand/dark.css' %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'assets/css/layout/aside/dark.css' %}" rel="stylesheet" type="text/css"/>
<!--end::Layout Themes-->

templates/base/header.html
{% load static %}
<!--begin::Header-->
<div id="kt_header" class="header  header-fixed ">
    <!--begin::Container-->
    <div class=" container-fluid  d-flex align-items-stretch justify-content-between">
        <div class="header-menu-wrapper header-menu-wrapper-left" id="kt_header_menu_wrapper"></div>

        <div class="topbar">
            <!--begin::User-->
            <div class="topbar-item">
                <div class="btn btn-icon btn-icon-mobile w-auto btn-clean d-flex align-items-center btn-lg px-2"
                     id="kt_quick_user_toggle">
                    <span class="text-muted font-weight-bold font-size-base d-none d-md-inline mr-1">Hola,</span>
                    <span class="text-dark-50 font-weight-bolder font-size-base d-none d-md-inline mr-3">{{ request.user.first_name }}</span>
                    <span class="symbol symbol-lg-35 symbol-25 symbol-light-success">
                        <span class="symbol-label font-size-h5 font-weight-bold">{{ request.user.first_name|first }}</span>
                    </span>
                </div>
            </div>
            <!--end::User-->
        </div>
        <!--end::Topbar-->
    </div>
    <!--end::Container-->
</div>
<!--end::Header-->

templates/base/js.html
{% load static %}

<!--begin::Global Config(global config for global JS scripts)-->
<script>
  var KTAppSettings = {
    "breakpoints": {
      "sm": 576,
      "md": 768,
      "lg": 992,
      "xl": 1200,
      "xxl": 1400
    },
    "colors": {
      "theme": {
        "base": {
          "white": "#ffffff",
          "primary": "#3699FF",
          "secondary": "#E5EAEE",
          "success": "#1BC5BD",
          "info": "#8950FC",
          "warning": "#FFA800",
          "danger": "#F64E60",
          "light": "#E4E6EF",
          "dark": "#181C32"
        },
        "light": {
          "white": "#ffffff",
          "primary": "#E1F0FF",
          "secondary": "#EBEDF3",
          "success": "#C9F7F5",
          "info": "#EEE5FF",
          "warning": "#FFF4DE",
          "danger": "#FFE2E5",
          "light": "#F3F6F9",
          "dark": "#D6D6E0"
        },
        "inverse": {
          "white": "#ffffff",
          "primary": "#ffffff",
          "secondary": "#3F4254",
          "success": "#ffffff",
          "info": "#ffffff",
          "warning": "#ffffff",
          "danger": "#ffffff",
          "light": "#464E5F",
          "dark": "#ffffff"
        }
      },
      "gray": {
        "gray-100": "#F3F6F9",
        "gray-200": "#EBEDF3",
        "gray-300": "#E4E6EF",
        "gray-400": "#D1D3E0",
        "gray-500": "#B5B5C3",
        "gray-600": "#7E8299",
        "gray-700": "#5E6278",
        "gray-800": "#3F4254",
        "gray-900": "#181C32"
      }
    },
    "font-family": "Poppins"
  };
</script>
<!--end::Global Config-->

<!--begin::Global Theme Bundle(used by all pages)-->
<script src="{% static 'vendors/global/plugins.bundle.js' %}"></script>
<script src="{% static 'assets/js/scripts.bundle.js' %}"></script>

<script src="{% static 'vendors/select2/django-select2.js' %}"></script>
<script src="{% static 'vendors/select2/dependent_fields.js' %}"></script>

<script src="{% static 'assets/js/forms/inputmask.js' %}"></script>
<script src="{% static 'assets/js/forms/select2.js' %}"></script>
<script src="{% static 'assets/js/messages.js' %}"></script>
<script>
    dependent_fields()
</script>
<!--end::Global Theme Bundle-->

<!--begin::Page Vendors(used by this page)-->
<!--end::Page Vendors-->

<!--begin::Page Scripts(used by this page)-->
<!--end::Page Scripts-->

templates/base/navbar.html
<!--begin::Subheader-->
<div class="subheader py-2 py-lg-6  subheader-solid " id="kt_subheader">
    <div class=" container-fluid  d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
        <div class="d-flex align-items-center flex-wrap mr-1">
            <div class="d-flex align-items-baseline flex-wrap mr-5">
                <h5 class="text-dark font-weight-bold my-1 mr-5">{{ site.title|capfirst }}</h5>
            </div>
        </div>

    </div>
</div>
<!--end::Subheader-->

templates/base/paginator.html
<!--begin::Pagination-->
{% if is_paginated %}
<div class="d-flex justify-content-center align-items-center flex-wrap">
    <div id="id_paginator" class="d-flex flex-wrap py-2 mr-3">

        {% if page_obj.has_previous %}
            <a href="#" data-page="{{ page_obj.previous_page_number }}" class="btn btn-icon btn-sm btn-light-primary mr-2 my-1">
                <i class="ki ki-bold-arrow-back icon-xs"></i>
            </a>
            {% if page_obj.number > 4 %}
            <a href="#" data-page="1" class="btn btn-icon btn-sm btn-light-primary mr-2 my-1">1</a>
            {% endif %}
        {% else %}
            <a href="#" class="btn btn-icon btn-sm btn-light-primary mr-2 my-1 disabled">
                <i class="ki ki-bold-arrow-back icon-xs"></i>
            </a>
        {% endif %}

        {% if page_obj.number|add:'-3' > 1 %}
            <a href="#" class="btn btn-icon btn-sm border-0 btn-hover-primary mr-2 my-1" data-page="{{ page_obj.number|add:'-4' }}">&hellip;</a>
        {% endif %}

        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <a href="javascript:void(0);" class="btn btn-icon btn-sm border-0 btn-hover-primary active mr-2 my-1">{{ i }}</a>
            {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %}
            <a href="#" data-page="{{ i }}" class="btn btn-icon btn-sm border-0 btn-hover-primary mr-2 my-1">{{ i }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.paginator.num_pages > page_obj.number|add:'3' %}
            <a href="#" data-page="{{ page_obj.number|add:'4' }}" class="btn btn-icon btn-sm border-0 btn-hover-primary mr-2 my-1">&hellip;</a>
        {% endif %}

        {% if page_obj.has_next %}
            {% if page_obj.number|add:'3' < paginator.num_pages %}
                <a href="#" data-page="{{ paginator.num_pages }}" class="btn btn-icon btn-sm btn-light-primary mr-2 my-1">{{ paginator.num_pages }}</a>
            {% endif %}
            <a href="#" data-page="{{ page_obj.next_page_number }}" class="btn btn-icon btn-sm btn-light-primary mr-2 my-1">
                <i class="ki ki-bold-arrow-next icon-xs"></i>
            </a>
        {% else %}
        <a href="#" class="btn btn-icon btn-sm btn-light-primary disabled mr-2 my-1">
            <i class="ki ki-bold-arrow-next icon-xs"></i>
        </a>
        {% endif %}
    </div>
</div>
{% endif %}
<!--end:: Pagination-->

templates/base/sidebar.html
{% load static %}
<!--begin::Aside-->
<div class="aside aside-left  aside-fixed  d-flex flex-column flex-row-auto" id="kt_aside">
    <!--begin::Brand-->
    <div class="flex-column-auto brand mt-10" id="kt_brand">
        <!--begin::Logo-->
        <a href="/" class="brand-logo">
            INTERNATIONAL SPY AGENCY
        </a>
        <!--end::Logo-->

    </div>
    <!--end::Brand-->

    <!--begin::Aside Menu-->
    <div class="aside-menu-wrapper flex-column-fluid" id="kt_aside_menu_wrapper">
        <!--begin::Menu Container-->
        <div id="kt_aside_menu" class="aside-menu mb-10" data-menu-vertical="1" data-menu-scroll="1"
             data-menu-dropdown-timeout="500">
            <!--begin::Menu Nav-->
            <ul class="menu-nav">
                <li class="menu-section">
                    <h4 class="menu-text">MAIN</h4>
                    <i class="menu-icon ki ki-bold-more-hor icon-md"></i>
                </li>
                <li class="menu-item" aria-haspopup="true" data-menu-toggle="hover">
                    <a href="{% url 'auth:login' %}" class="menu-link menu-toggle">
                        {% include 'svg/icon.html' %}
                        <span class="menu-text">HOME</span>
                    </a>
                </li>
                <li class="menu-section">
                    <h4 class="menu-text">PAGES</h4>
                    <i class="menu-icon ki ki-bold-more-hor icon-md"></i>
                </li>
                <li class="menu-item" aria-haspopup="true" data-menu-toggle="hover">
                    <a href="{% url 'auth:hitman_list' %}" class="menu-link menu-toggle">
                        {% include 'svg/icon.html' %}
                        <span class="menu-text">HITMAN</span>
                    </a>
                </li>
                <li class="menu-item" aria-haspopup="true" data-menu-toggle="hover">
                    <a href="{% url 'hit:hits_list' %}" class="menu-link menu-toggle">
                        {% include 'svg/icon.html' %}
                        <span class="menu-text">HITS</span>
                    </a>
                </li>
            </ul>
            <!--end::Menu Nav-->
        </div>
        <!--end::Menu Container-->
    </div>
    <!--end::Aside Menu-->
</div>
<!--end::Aside-->

templates/base/user_panel.html
{% load static %}
<!-- begin::User Panel-->
<div id="kt_quick_user" class="offcanvas offcanvas-right p-10">
    <!--begin::Header-->
    <div class="offcanvas-header d-flex align-items-center justify-content-between pb-5">
        <h3 class="font-weight-bold m-0">
            Perfil de Usuario
        </h3>
        <a href="#" class="btn btn-xs btn-icon btn-light btn-hover-primary" id="kt_quick_user_close">
            <i class="ki ki-close icon-xs text-muted"></i>
        </a>
    </div>
    <!--end::Header-->

    <!--begin::Content-->
    <div class="offcanvas-content pr-5 mr-n5">
        <!--begin::Header-->
        <div class="d-flex align-items-center mt-5">

            <div class="d-flex flex-column">
                <a href="#" class="font-weight-bold font-size-h5 text-dark-75 text-hover-primary">
                    {{ request.user.get_full_name }}
                </a>
                <div class="navi mt-2">
                    <a href="#" class="navi-item">
                        <span class="navi-link p-0 pb-2">
                            <span class="navi-icon mr-1">
                                <span class="svg-icon svg-icon-lg svg-icon-primary"><!--begin::Svg Icon | path:assets/media/svg/icons/Communication/Mail-notification.svg-->
                                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                        <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                            <rect x="0" y="0" width="24" height="24"/>
                                            <path
                                                d="M21,12.0829584 C20.6747915,12.0283988 20.3407122,12 20,12 C16.6862915,12 14,14.6862915 14,18 C14,18.3407122 14.0283988,18.6747915 14.0829584,19 L5,19 C3.8954305,19 3,18.1045695 3,17 L3,8 C3,6.8954305 3.8954305,6 5,6 L19,6 C20.1045695,6 21,6.8954305 21,8 L21,12.0829584 Z M18.1444251,7.83964668 L12,11.1481833 L5.85557487,7.83964668 C5.4908718,7.6432681 5.03602525,7.77972206 4.83964668,8.14442513 C4.6432681,8.5091282 4.77972206,8.96397475 5.14442513,9.16035332 L11.6444251,12.6603533 C11.8664074,12.7798822 12.1335926,12.7798822 12.3555749,12.6603533 L18.8555749,9.16035332 C19.2202779,8.96397475 19.3567319,8.5091282 19.1603533,8.14442513 C18.9639747,7.77972206 18.5091282,7.6432681 18.1444251,7.83964668 Z"
                                                fill="#000000"/>
                                            <circle fill="#000000" opacity="0.3" cx="19.5" cy="17.5" r="2.5"/>
                                        </g>
                                    </svg><!--end::Svg Icon-->
                                </span>
                            </span>
                            <span class="navi-text text-muted text-hover-primary">{{ request.user.email }}</span>
                        </span>
                    </a>
                    <a href="{% url 'auth:logout' %}" class="btn btn-sm btn-light-primary font-weight-bolder py-2 px-5">Cerrar sesión</a>
                </div>
            </div>
        </div>


    </div>
    <!--end::Content-->
</div>
<!-- end::User Panel-->