apps/authentication/urls.py
"""Auth models."""

# Django
from django.contrib.auth.views import (
    LogoutView,
    LoginView,
)
from django.urls import path

# Views
from apps.authentication.views import (
    SignUpView,
    HitmanListView,
    HitmanDetailView,
    AddFromManagersGroupView,
)

app_name = "auth"

urlpatterns = (
    path(
        route="",
        view=LoginView.as_view(
            template_name="authentication/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path(
        route="logout/",
        view=LogoutView.as_view(),
        name="logout",
    ),
    path(
        route="register/",
        view=SignUpView.as_view(),
        name="register",
    ),
    path(
        route="hitman/",
        view=HitmanListView.as_view(),
        name="hitman_list",
    ),
    path(
        route="hitman/<int:pk>/",
        view=HitmanDetailView.as_view(),
        name="hitman_detail",
    ),
    path(
        route="hitman/<int:pk>/add/managers/",
        view=AddFromManagersGroupView.as_view(),
        name="hitman_add_managers",
    ),
)

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib.auth.decorators import login_required

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.authentication.urls")),
    path("", include("apps.hit.urls")),
    path("", include("apps.bulk.urls")),
    path("", include("apps.fsm.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/authentication/models.py
"""User model."""
# Django core
from django.contrib.auth.models import AbstractUser
from django.db import models
from django_fsm import FSMIntegerField, transition
from .service import CheckRol


class User(AbstractUser):
    """User model.

    Extend from Django's Abstract User, change the username field
    to email and add some extra fields.
    """

    class StatusChoices(models.IntegerChoices):
        """Class define choices"""

        ACTIVE = 1, "ACTIVE"
        INACTIVE = 2, "INACTIVE"

    email = models.EmailField(
        unique=True,
        error_messages={"unique": "A user with this email already exists"},
    )
    state = FSMIntegerField(
        choices=StatusChoices.choices,
        default=StatusChoices.ACTIVE,
        protected=True,
        verbose_name="Status",
    )
    managers = models.ForeignKey(
        "self",
        on_delete=models.PROTECT,
        null=True,
        verbose_name="Jefe",
    )
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    class Meta:
        """Class define meta information"""

        verbose_name = "User"
        verbose_name_plural = "Users"

    def __str__(self):
        """Return username."""
        return self.username

    @property
    def rol(self):
        return CheckRol.rol(self)

    @transition(
        field="state",
        source=StatusChoices.ACTIVE,
        target=StatusChoices.ACTIVE,
        custom=dict(verbose="ACTIVE"),
    )
    def active(self, **kwargs):
        """Method to correct procedure"""
        pass

    @transition(
        field="state",
        source=StatusChoices.ACTIVE,
        target=StatusChoices.INACTIVE,
        custom=dict(verbose="INACTIVE"),
    )
    def inactive(self, **kwargs):
        """Method to correct procedure"""
        self.is_active = False

apps/authentication/forms.py
# Django
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User


class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "email",
            "password1",
            "password2",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"

    def save(self, commit=True):
        obj = super().save(commit=False)
        obj.username = obj.email
        if commit:
            obj.save()
        return obj


class HitmanUpdateForm(forms.ModelForm):
    hitmans = forms.ModelMultipleChoiceField(
        queryset=User.objects.exclude(id=1).filter(
            is_active=True, managers__isnull=True
        ),
        label="Add hitman",
    )

    class Meta:
        model = User
        fields = (
            "username",
            "hitmans",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"
        self.fields["username"].widget.attrs["readonly"] = True

    def save(self, commit=True):
        obj = super().save(commit=False)
        queryset = self.cleaned_data.get("hitmans")
        for query in queryset:
            query.managers = obj
            query.save()
        obj.save()
        return obj

apps/authentication/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView

from apps.authentication.forms import RegisterUserForm, HitmanUpdateForm
from apps.authentication.models import User
from config.views import BaseListView, BaseDetailView, BaseUpdateView
from .utils import check_big_boss, check_managers


class SignUpView(SuccessMessageMixin, CreateView):
    """Class define register de user"""

    form_class = RegisterUserForm
    template_name = "authentication/register.html"
    success_url = reverse_lazy("auth:login")
    success_message = "Your profile was created successfully"


class HitmanUrlsMixin:
    """Mixin create urls base"""

    def get_context_data(self, **kwargs):
        """Overwrite contexto"""
        context = super().get_context_data(**kwargs)
        urls = {"list": reverse("auth:hitman_list")}
        opts = {"title": "Hitman", "urls": urls}
        if "site" in context:
            context.get("site").update(opts)
        else:
            context.update({"site": opts})
        return context


class HitmanListView(HitmanUrlsMixin, LoginRequiredMixin, BaseListView):
    """Class define list de hitman"""

    model = User
    template_name = "hitman/hitman_list.html"
    list_fields = ("email", "get_full_name:full name", "state", "rol:roles")

    def dispatch(self, request, *args, **kwargs):
        user = self.request.user
        if not user.is_authenticated:
            return self.handle_no_permission()
        if check_big_boss(user) or check_managers(user):
            return super().dispatch(request, *args, **kwargs)
        raise PermissionDenied

    def get_queryset(self):
        """Overwrite method queryset apply filter depende the rol"""
        queryset = super().get_queryset().exclude(id=1)
        user = self.request.user
        if check_big_boss(user):
            return queryset
        if check_managers(user):
            hitmans = self.model.objects.filter(managers=user)
            hitmans = [user.pk for user in hitmans]
            hitmans += [user.pk]
            return queryset.filter(pk__in=list(hitmans))
        return queryset.none()


class HitmanDetailView(HitmanUrlsMixin, LoginRequiredMixin, BaseDetailView):
    """Class define the detail hitman"""

    model = User
    template_name = "hitman/hitman_detail.html"
    detail_fields = ("email", "first_name", "last_name")

    def dispatch(self, request, *args, **kwargs):
        user = self.request.user
        if not user.is_authenticated:
            return self.handle_no_permission()
        if check_big_boss(user) or check_managers(user):
            return super().dispatch(request, *args, **kwargs)
        raise PermissionDenied

    def get_context_data(self, **kwargs):
        """Overwrite get context data send list hitmans for users"""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        hitmans = User.objects.filter(managers=user)
        context.update({"hitmans": hitmans})
        return context


class AddFromManagersGroupView(HitmanUrlsMixin, LoginRequiredMixin, BaseUpdateView):
    """Class define add hitman to managers"""

    model = User
    form_class = HitmanUpdateForm
    template_name = "base/base_form.html"

    def dispatch(self, request, *args, **kwargs):
        user = self.request.user
        if not user.is_authenticated:
            return self.handle_no_permission()
        if check_big_boss(user):
            return super().dispatch(request, *args, **kwargs)
        raise PermissionDenied

    def get_success_url(self):
        """Method redirect detail hitman"""
        return reverse(
            "auth:hitman_detail",
            kwargs={
                "pk": self.object.id,
            },
        )

    def get_context_data(self, **kwargs):
        """Overwrite get context data send list hitmans for users"""
        context = super().get_context_data(**kwargs)
        if "site" in context:
            context.get("site").update({"title": "Add From Managers Group"})
        return context


# class RemoveFromManagersGroupView

apps/authentication/templates/authentication/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Title -->
    <title>:: SPY :: AGENCY</title>
    {% block css %}
        {% include 'base/css.html' %}
        <!-- Theme Styles -->
        <link href="{% static 'login/css/main.min.css' %}" rel="stylesheet">
        <link href="{% static 'login/css/custom.css' %}" rel="stylesheet">
    {% endblock %}
</head>
<body class="login-page">
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-12 col-lg-4">
            <div class="card login-box-container">
                {% block form %}
                    <!--begin::Login Sign in form-->
                    <!--end::Login Sign in form-->
                {% endblock %}
            </div>
        </div>
    </div>
</div>

{% block js %}
    {% include 'base/js.html' %}
    <script src="{% static 'login/js/main.min.js' %}"></script>
{% endblock %}
</body>
</html>

apps/authentication/templates/authentication/css.html
{% load static %}
<!-- Styles -->
<link href="https://fonts.googleapis.com/css?family=Poppins:400,500,700,800&display=swap" rel="stylesheet">
<link href="{% static 'login/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


<!-- Theme Styles -->
<link href="{% static 'login/css/main.min.css' %}" rel="stylesheet">
<link href="{% static 'login/css/custom.css' %}" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

apps/authentication/templates/authentication/js.html
{% load static %}
<!-- Javascripts -->
<script src="{% static 'login/plugins/jquery/jquery-3.4.1.min.js' %}"></script>
<script src="https://unpkg.com/@popperjs/core@2"></script>
<script src="{% static 'login/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="https://unpkg.com/feather-icons"></script>
<script src="{% static 'login/js/main.min.js' %}"></script>

apps/authentication/templates/authentication/login.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block form %}
    <!--begin::Login Sign in form-->
    <div class="card-body">
        <div class="authent-logo">
            <img src="{% static 'assets/images/logo@2x.png' %}" alt="">
        </div>
        <div class="authent-text">
            <p>Welcome to SPY!</p>
            <p>Please Sign-in to your account.</p>
        </div>
        <form class="form g-3 needs-validation" novalidate="" method="POST">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="mb-3">
                <div class="form-floating">
                    <label for="floatingInput">Email address</label>
                    {% if form.username.errors %}
                        <div class="invalid-feedback d-block">{{ form.username.errors }}</div>
                    {% endif %}
                    <input type="email" class="form-control invalid" id="floatingInput"
                           placeholder="name@example.com" name="username">
                </div>
            </div>
            <div class="mb-3">
                <div class="form-floating">
                    <label for="floatingPassword">Password</label>
                    {% if form.password.errors %}
                        <div class="invalid-feedback d-block">{{ form.password.errors }}</div>
                    {% endif %}
                    <input type="password" class="form-control" id="floatingPassword"
                           placeholder="Password" name="password">

                </div>
            </div>
            <div class="d-grid">
                <button type="submit" class="btn btn-info m-b-xs">Sign In</button>
            </div>
        </form>
        <div class="authent-reg">
            <p>Not registered? <a href="{% url 'auth:register' %}">Create an account</a></p>
        </div>
    </div>
    <!--end::Login Sign in form-->
{% endblock %}

apps/authentication/templates/authentication/register.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block css %}
    {{ block.super }}
    <style>
        .error-list {
            color: #f75d6fd8;
            margin-top: .25rem;
            font-size: .875em;
        }
    </style>
{% endblock %}
{% block form %}
    <div class="card-body">
        <div class="authent-logo">
            <img src="{% static 'assets/images/logo@2x.png' %}" alt="">
        </div>
        <div class="authent-text">
            <p>Welcome to SPY!</p>
            <p>Enter your details to create your account</p>
        </div>
        <form class="form g-3 needs-validation" novalidate="" method="POST">
            {% csrf_token %}
            {% for field in form.hidden_fields %}
                {{ field }}
            {% endfor %}
            {% for field in form.visible_fields %}
                <label for="{{ field.id_for_label }}" class="mt-2">{{ field.label }}</label>
                <div class="error-list">{{ field.errors }}</div>
                {{ field }}
                <div class="form-text">{{ field.help_text }}</div>
            {% endfor %}
            <div class="d-grid mt-3">
                <button type="submit" class="btn btn-primary m-b-xs">Register</button>
            </div>
        </form>
        <div class="authent-login">
            <p>Already have an account? <a href="{% url 'auth:login' %}">Sign in</a></p>
        </div>
    </div>
{% endblock %}